### PR TITLE
EASYOPAC-258 - Back cover for ddbcms project.

### PR DESCRIPTION
**Pull request by makcumm**

### CODE REVIEW

**Comment by OIOIOOOI** [comment]
| `ting_covers_backside.module:27` |
| --- |

Please use the built-in REQUEST_TIME constant.
https://api.drupal.org/api/drupal/includes!bootstrap.inc/constant/REQUEST_TIME/7.x

**Comment by OIOIOOOI** [comment]
What's the purpose to add same file twice?

**Comment by OIOIOOOI** [comment]
| `ting_covers_backside.module:96` |
| --- |

I.e. module_invoke/drupal_alter, depending on the implementation.

**Comment by avoykov** [comment]
|`ting_covers_backside.module:96`|
|---|
Test

**Comment by avoykov** [comment]
|`ting_covers_backside.module:75`|
|---|
test

**Pull request merged**
